### ISSUE TITLE
New JSON databases get created as directories instead of files

### ISSUE THREAD

**Issue by Arcensoth** [CommanderBot-Dev/commanderbot-ext#28]
When an extension creates a new JSON database file automatically, it creates a directory instead of an empty file. This is likely a simple fix regarding `pathlib` and the `Path` object.

This currently happens with:
- `faq`
- `invites`
- `roles`

**Comment by lolgeny** [comment]
Note that you need to add a version to this, if you just create a file without adding it it still doesn't work

**Comment by Arcensoth** [comment]
Fixed by #33
